version: 2
updates:
  - directory: "/"
    groups:
      dependencies:
        patterns:
          - "*"
    package-ecosystem: "npm"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "America/Toronto"
    target-branch: "develop"
