services:
  dev_environment:
    entrypoint:
      - sleep
      - infinity
    image: docker/dev-environments-javascript:stable-1
    init: true
    volumes:
      - source: /var/run/docker.sock
        target: /var/run/docker.sock
        type: bind
