'use client';

import type { FC } from 'react';

import styles from './page.module.css';

const Page: FC = () => {
  return (
    <div>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
      <p>hello world</p>
    </div>
  );
};

export default Page;
